// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // `prisma generate` (run in postinstall) only reads the schema — it never
    // opens a DB connection — so this must not hard-fail when DATABASE_URL is
    // absent (e.g. Cloudflare Workers Builds only inject dashboard "Variables
    // & Secrets" into the deployed Worker at request time, not into the
    // npm install/build container). `env()` throws on a missing var; plain
    // process.env does not.
    url: process.env.DATABASE_URL ?? "",
  },
});
